### ISSUE TITLE
View and build the Device Tree Wiki Page - outdated

### ISSUE THREAD

**Issue by fweinrebe** [ArrowElectronics/data-storm-daq#3]
The "View and build the Device Tree"  Wiki Page is seriously not up to speed. If you follow the steps as on the page, then you end up in a directory that does not have the page you are supposed to edit and make.

By the time you get to this step, one is not in the <home>/datastorm_daq/linux folder. So the path /arch/arm/boot/dts/.... is not relative. There is a cd command missing in the guide. Although it is mentioned, it is not listed as a step. 

Please revise. It causes confusion.

**Comment by skravats** [comment]
Hi @fweinrebe . Apologies for the no response. 

The previous page https://github.com/ArrowElectronics/data-storm-daq/wiki/Linux-Kernel#build-with-kernel 

step 4  is 

cd linux. The user should still be in this directory when trying to view the dts file. I ran through the steps to verify it still worked.

Thanks for the message.

skravats
